-- Create admin user in auth.users table
INSERT INTO auth.users (
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  phone_confirmed_at,
  confirmation_sent_at,
  recovery_sent_at,
  email_change_sent_at,
  new_email,
  new_phone,
  invited_at,
  action_link,
  email_change,
  email_change_confirm_status,
  banned_until,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change_token_current,
  email_change_token_new,
  instance_id,
  last_sign_in_at
) VALUES (
  '00000000-0000-0000-0000-000000000001'::uuid,
  'authenticated',
  'authenticated',
  '1234567890@sidehuddle.app',
  crypt('phone_1234567890_verified', gen_salt('bf')),
  now(),
  now(),
  now(),
  now(),
  now(),
  '',
  '',
  null,
  '',
  '',
  0,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"display_name": "Test Admin", "username": "test_admin", "phone_number": "+1234567890"}',
  false,
  now(),
  now(),
  '+1234567890',
  '',
  '',
  now(),
  now(),
  '',
  '',
  '00000000-0000-0000-0000-000000000000',
  null
) ON CONFLICT (id) DO UPDATE SET
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  updated_at = now();

-- Update the existing admin profile to use a working phone number
UPDATE profiles 
SET phone_number = '+1234567890'
WHERE user_id = '00000000-0000-0000-0000-000000000001';